spring:
    main:
        allow-circular-references: true
    datasource:
        url: jdbc:postgresql://localhost:5432/achievements_hunt
        username: achievements_hunt_bot
        password: db
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        database: postgresql
        defer-datasource-initialization: true
    sql:
        init:
            mode: never